version: '3.9'
services:
  mysql:
    build:
      args:
        mysqlVersion: ${MYSQL_VERSION}
      context: .
      dockerfile: Dockerfiles/mysql.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    entrypoint:
      - bash
      - /usr/src/database/Scripts/initDB.sh
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_db_pw
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pw
      MYSQL_USER: ${MYSQL_USER}
    networks:
      pintent_app:
    ports:
      - '3306:3306'
    secrets:
      - mysql_root_pw
      - mysql_db_pw
    volumes:
      - mysqlVSConfig:/home/node/.vscode-server:rw
      - ./Mysql/Installation:/var/lib/mysql
      - ./Mysql/Database:/docker-entrypoint-initdb.d/
      - ./Mysql/Scripts:/usr/src/database/Scripts
      # - ./Mysql/Database:/usr/src/******/Database

    working_dir: /usr/src/database
  
  api:
    build:
      args:
        node_version: ${API_VERSION_PROM}
      context: .
      dockerfile: Dockerfiles/api.Dockerfile
      target: $MODE_NODE_SERVER
    container_name: api
    depends_on:
      - mysql
    environment:
      CHOKIDAR_USEPOLLING: 'true'
      NODE_ENV: ${MODE_NODE_SERVER}
      MYSQL_DB: ${MYSQL_DATABASE}
      MYSQL_PW: /run/secrets/mysql_db_pw
      MYSQL_USER: ${MYSQL_USER}
    # mem_limit: 2500m
    networks:
      pintent_app:
    ports:
      - 8000:8000 # server port
      - 9228:9228 # vscode port
      - 9100:9100 # prometheus client port
    secrets:
        - mysql_db_pw
    user: node
    volumes:
      - nodeJSVSConfig:/home/node/.vscode-server:rw
      - ./Backend:/var/app/backend
      - node_modules_api_PintentApp:/var/app/backend/node_modules

    working_dir: /var/app/backend
    # command: npm start

  react:
    build:
      args:
        node_version: ${REACT_VERSION}
      context: .
      dockerfile: Dockerfiles/react.Dockerfile
      target: $MODE_REACT_CLIENT
    container_name: react
    # command: npm start
    mem_limit: 2000m
    environment:
      # FAST_REFRESH: 'false'
      CHOKIDAR_USEPOLLING: 'true'
      REACT_APP_FOR: dEVELOP
    links:
      - api
    networks:
      pintent_app:
    ports:
      - 3000:3000 # client port
      - 9229:9229 # vscode port
    user: node
    volumes:
      - reactVSConfig:/home/node/.vscode-server:rw
      - ./Frontend:/var/app/frontend
      # - ./Backend:/var/app/backend
      - node_modules_cli_PintentApp:/var/app/frontend/node_modules
    # restart: always
    
    working_dir: /var/app/frontend
  
secrets:
  mysql_db_pw:
    file: ./Mysql/Passwords/${MYSQL_PW_FILE}
  mysql_root_pw:
    file: ./Mysql/Passwords/${MYSQL_PW_ROOT_FILE}

networks:
  pintent_app:
    driver: bridge
    name: pintent_app

volumes:
  node_modules_api_PintentApp:
  node_modules_cli_PintentApp:
  reactVSConfig:
  mysqlVSConfig:
  nodeJSVSConfig:
  # Backend:
