services:
  # couchbase:
  #   image: couchbase:7.1.1
  #   ports:
  #     - 8091-8097:8091-8097
  #     - 11210:11210
  #     - 11207:11207
  #     - 18091-18095:18091-18095
  #     - 18096:18096
  #     - 18097:18097

  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server
          /usr/local/etc/redis/redis.conf
          --requirepass jiqopvnzuwng
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    secrets:
      - mysql_db_pw
    networks:
      pintent_app:
    
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mysql_db_pw
    secrets:
      - mysql_db_pw
    networks:
      pintent_app:
    
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mysql_root_pw
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mysql_db_pw
    networks:
      pintent_app:
    secrets:
      - mysql_root_pw
      - mysql_db_pw


networks:
  pintent_app:
    external: true

secrets:
  mysql_db_pw:
    file: ./Mysql/Passwords/${MYSQL_PW_FILE}
  mysql_root_pw:
    file: ./Mysql/Passwords/${MYSQL_PW_ROOT_FILE}
